services:
  nest-app:
    image: nest-app
    build: .
    
  web:
    image: nginx:alpine
    ports:
      - "3002:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nest-app
    